openapi: 3.0.1
info:
  title: backend
  version: '1.0'
paths:
  /health:
    get:
      tags:
        - backend
      operationId: Health Check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /task:
    post:
      tags:
        - backend
      operationId: Add Task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDTO'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
    get:
      tags:
        - backend
      operationId: Get All Tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskDTO'
  '/task/{id}':
    get:
      tags:
        - backend
      operationId: Get Task by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        '404':
          description: Not Found
    delete:
      tags:
        - backend
      operationId: Delete Task by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: No Content
components:
  schemas:
    TaskDTO:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        isCompleted:
          type: boolean
      additionalProperties: false