GET http://0.0.0.0:5000/task

###

POST http://0.0.0.0:5000/task
Content-Type: application/json

{
    "name": "Demo 3",
    "isCompleted": false
}

###

GET http://0.0.0.0:5000/task/1

###

DELETE http://0.0.0.0:5000/task/1
