GET http://localhost:5068/todos

###

POST http://localhost:5068/todos
Content-Type: application/json

{
    "name": "Demo",
    "dueDate": "2024-12-31",
    "isCompleted": false
}

###

GET http://localhost:5068/todos/0

###

DELETE http://localhost:5068/todos/1
